name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        run: |
          make build_linux_386
          make build_linux_amd64
          make build_linux_arm
          make build_linux_arm64
          make build_windows_386
          make build_windows_amd64
      - name: Test
        run: go test -v ./...
      - uses: actions/upload-artifact@v2
        with:
          name: tier2pool_linux_386
          path: ./build/tier2pool_linux_386
      - uses: actions/upload-artifact@v2
        with:
          name: tier2pool_linux_amd64
          path: ./build/tier2pool_linux_amd64
      - uses: actions/upload-artifact@v2
        with:
          name: tier2pool_linux_arm
          path: ./build/tier2pool_linux_arm
      - uses: actions/upload-artifact@v2
        with:
          name: tier2pool_linux_arm64
          path: ./build/tier2pool_linux_arm64
      - uses: actions/upload-artifact@v2
        with:
          name: tier2pool_windows_386
          path: ./build/tier2pool_windows_386.exe
      - uses: actions/upload-artifact@v2
        with:
          name: tier2pool_windows_amd64
          path: ./build/tier2pool_windows_amd64.exe
